### ISSUE TITLE
quick question on sphere textures

### ISSUE THREAD

**Issue by grburgess** [deeplook/spheromones#4]
Hi! Thank you very much for these examples. I am trying to map the image of Earth into a sphere, but can't understand the u,v arguments. Did you ever update this to include proper sphere plotting? Thanks!

**Comment by deeplook** [comment]
Hi! No, I didn't, sorry. I guess it wasn't clear to me either. I remember I was asking some questions as issues in https://github.com/maartenbreddels/ipyvolume, but was left with the impression that it is no longer much maintained. There is this gitter which you might consult instead, maybe: https://gitter.im/maartenbreddels/ipyvolume. If you get it working or any response at all please let me know.

**Comment by grburgess** [comment]
I found a non-ideal workaround. Instead of using the textures, I just use the RGB values directly and plot them. This uses a massive amount of memory.

First I store the images precomputed on a sphere in HDF5:

https://github.com/grburgess/gbmgeometry/blob/master/gbmgeometry/utils/file_converters.py#L86

then I have a class for plotting.animating spheres:

https://github.com/grburgess/gbmgeometry/blob/master/gbmgeometry/geometry/sphere.py#L11

It works well, but if you want to save the widgets for docs or animate the objects with images... you need a super computer and a GBs of space.

**Comment by grburgess** [comment]
Actually... I have now solved it!

The trick was learning what these UV mappings were.
So, the above links have changed:

https://github.com/grburgess/gbmgeometry/blob/master/gbmgeometry/geometry/sphere.py#L74

**Comment by deeplook** [comment]
Done with https://github.com/deeplook/spheromones/pull/5. Thanks!
